### PR TITLE
GP-2892. add md5sum checks to calculate script

### PR DESCRIPTION
**Pull request by rjovelin**
- calculate script more robust with md5sum checks
- added engineArguments to vidarrtest-regression.json.in

### CODE REVIEW

**Comment by rjovelin** [comment]
test this please

**Comment by rjovelin** [comment]
retest this please

**Comment by rjovelin** [comment]
retest this please

**Comment by rjovelin** [comment]
retest this please

**Review by mlaszloffy — APPROVED** [review]

**Review by pruzanov — APPROVED** [review]

**Pull request merged**
